#ifndef LEXER_H
#define LEXER_H

typedef enum {
    TOKEN_KEYWORD_NUM,
    TOKEN_KEYWORD_STR,
    TOKEN_KEYWORD_LIST,
    TOKEN_KEYWORD_VAR,
    TOKEN_KEYWORD_NIL,
    TOKEN_KEYWORD_IF,
    TOKEN_KEYWORD_ELIF,
    TOKEN_KEYWORD_ELSE,
    TOKEN_KEYWORD_WHILE,
    TOKEN_KEYWORD_PRINT,
    TOKEN_KEYWORD_FUN,
    TOKEN_KEYWORD_CALL,
    TOKEN_KEYWORD_RETURN,
    TOKEN_IDENTIFIER,
    TOKEN_NUMBER,
    TOKEN_STRING,
    TOKEN_OPERATOR_CONCAT,
    TOKEN_OPERATOR_PLUS,
    TOKEN_OPERATOR_PLUS_PLUS,
    TOKEN_OPERATOR_MINUS,
    TOKEN_OPERATOR_MINUS_MINUS,
    TOKEN_OPERATOR_MULTIPLY,
    TOKEN_OPERATOR_DIVIDE,
    TOKEN_OPERATOR_MODULO,
    TOKEN_OPERATOR_POWER,
    TOKEN_OPERATOR_BITWISE_AND,
    TOKEN_OPERATOR_BITWISE_OR,
    TOKEN_OPERATOR_BITWISE_XOR,
    TOKEN_OPERATOR_LESS,
    TOKEN_OPERATOR_LESS_EQUAL,
    TOKEN_OPERATOR_GREATER,
    TOKEN_OPERATOR_GREATER_EQUAL,
    TOKEN_OPERATOR_EQUAL,
    TOKEN_OPERATOR_NOT_EQUAL,
    TOKEN_OPERATOR_NOT,
    TOKEN_OPERATOR_LOGICAL_AND,
    TOKEN_OPERATOR_LOGICAL_OR,
    TOKEN_OPERATOR_LOGICAL_XOR,
    TOKEN_SEMICOLON,
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_COMMA,
    TOKEN_EOF,
    TOKEN_ERROR,
    TOKEN_ELIF
} TokenType;

typedef struct {
    TokenType type;
    char *lexeme;
    double num_value;
    char *str_value;
    struct ListNode *list_value;
} Token;

typedef struct {
    const char *source;
    int current_pos;
} Lexer;

void init_lexer(Lexer *lexer, const char *source);

Token next_token(Lexer *lexer);

#endif